### ISSUE TITLE
Generate a Gaussian noise dataset 

### ISSUE THREAD

**Issue by jrs65** [radiocosmology/draco#52] opened 2019-10-08 23:32 UTC
This task should:
- [ ] Use the noise estimates of an existing dataset to replace the data section (use the `weight` property).
- [ ] Support multiple container types. I'm not sure duck typing will work, because the data section has different names, and sometimes is real and sometimes complex, so you might need to specify the properties for different types of data
- [ ] Support both draco and CHIME timestream types without explicitly importing CHIME packages (this you may need to duck type)
- [ ] Efficiently generate random numbers (use `RandomGen` which is already a dependency)

@tristpinsm feel free to add items to this one.

**Comment by anjakefala** [comment] 2019-10-09 23:46
My understanding:
* The `weight` property is the estimate of the variance of the noise in each datasample.
* The task should zero all data and replace it with a realisation of a Gaussian noise distribution with a `visweight` variance.

Is the above correct?

**Comment by tristpinsm** [comment] 2019-10-09 23:48
that's right, except that `vis_weight` is actually the inverse variance

**Comment by anjakefala** [comment] 2019-10-09 23:50
@tristpinsm Thanks!

**Comment by anjakefala** [comment] 2019-10-15 23:29
Notes from meeting:

For a random generator, the following key things are needed:
* you want it to be reproducable
* you want it to be generating different arrays for each node and for each realisation

- [ ] for `mpi_random_seed`, the `extra` param takes care of generating a different array for each node. we also may want to have multiple reproducible realisations. Proposal is to either add a counter to tasks that employ it or the `mpi_random_seed` context manager keeps track of how often it was run.

**Comment by anjakefala** [comment] 2019-10-22 23:27
Do we want to update the other tasks to use `RandomGen` instead of `NumPy.random`?

**Comment by tristpinsm** [comment] 2019-10-22 23:45
Would the reason to do so be performance? Do we think using `numpy` is currently a limitation?

**Comment by anjakefala** [comment] 2019-10-22 23:46
I will look into the difference between them! I just noticed that @jrs65 recommended using `RandomGen` and elsewhere in `synthesis/noise.py` uses `NumPy.random`.

**Comment by tristpinsm** [comment] 2019-10-22 23:50
yeah I had never heard of `RandomGen` until now and I'm still not sure what its advantages are. From what I read in their docs it is supposed to be quite a bit faster in certain situations. They also note that compatibility (presumably between versions) is not guaranteed.

**Comment by tristpinsm** [comment] 2019-10-22 23:58
I think this has been integrated in `numpy` already: https://docs.scipy.org/doc/numpy/reference/random/generator.html#numpy.random.Generator. As long as we are running a recent version this functionality should already be available (?)

**Comment by jrs65** [comment] 2019-10-23 04:08
I don't think there's any reason to go back and change things, but as `RandomGen` is already a requirement we should use it when we can.

As @tristpinsm says the advantage is performance, and there are certain tasks (of which this will be one) where the speed of the RNG is the bottleneck. I introduced it for the delay power spectrum estimator (which in some sense internally does what your doing here hundreds of times), and it took it down from 40 mins per power spectrum to more like 10 mins.

**Comment by jrs65** [comment] 2019-10-23 04:12
I agree that it looks like it has been merged into numpy in 1.17 (or at least the core). I'd like to check that it still has the OpenMP parallel mode though before dropping the dependency.

**Comment by anjakefala** [comment] 2019-10-23 17:23
Understood!

The reason behind changing the original ones was to simplify the seed state. But if it is integrated into `NumPy` (I will check if it still has the OpenMP parallel mode), perhaps they share a `state`.

**Comment by anjakefala** [comment] 2019-10-23 18:51
So, seeding seems to work in different ways for the "legacy random" and the "new generators". 

`RandomState` provides access to legacy random https://numpy.org/devdocs/reference/random/generated/numpy.random.RandomState.get_state.html#numpy.random.RandomState.get_state. get_state/set_state/seed specifically work with the legacy randoms https://numpy.org/devdocs/reference/random/legacy.html?highlight=seed.

The new `RandomGenerator` works by initialising a generator with a seed https://numpy.org/devdocs/reference/random/generator.html#numpy.random.Generator. `SeedSequence` https://numpy.org/devdocs/reference/random/bit_generators/generated/numpy.random.SeedSequence.html#numpy.random.SeedSequence is the main class that determines the sequence of seeds. 

So if we bump to NumPy 1.17, it will be a bit of a refactor, and the two random generators do not intersect with their seed states.

**Comment by anjakefala** [comment] 2019-10-23 19:52
I cannot confirm whether it has OpenMP parallel mode, but I do not see anything in here that would indicate support being removed: https://github.com/numpy/numpy/pull/13163.

**Comment by tristpinsm** [comment] 2019-10-23 20:02
It seems like the changes are pretty significant between 1.16 and 1.17. Should we create an issue to migrate whatever uses the old `RandomState` methods to `Generator`s?

**Comment by anjakefala** [comment] 2019-10-23 21:19
@tristpinsm Agreed, they are big and out of scope for this issue/pr, and I think it would be good to do the migration.

**Closed** 2020-02-20 01:02 UTC
